### ISSUE TITLE
Floating objects can be swept onto the land

### ISSUE THREAD

**Issue by lordmauve** [larryhastings/pyweek26#18]
Objects in current can be swept onto the land:

![image](https://user-images.githubusercontent.com/617224/47616037-42d22380-daaf-11e8-9b92-65eb803e28aa.png)

Bisecting shows the bad commit is b96d92a3b9e1612eba27f911aeb6d76023c49213.

**Comment by lordmauve** [comment]
Without -O an assertion is tripped:

```
Traceback (most recent call last):
  File "src/game.py", line 2575, in <module>
    main(sys.argv[1:])
  File "src/game.py", line 2572, in main
    raise e
  File "src/game.py", line 2569, in main
    pyglet.app.run()
  File "/home/mauve/.virtualenvs/pyweek3/lib/python3.6/site-packages/pyglet/app/__init__.py", line 138, in run
    event_loop.run()
  File "/home/mauve/.virtualenvs/pyweek3/lib/python3.6/site-packages/pyglet/app/base.py", line 142, in run
    self._run()
  File "/home/mauve/.virtualenvs/pyweek3/lib/python3.6/site-packages/pyglet/app/base.py", line 154, in _run
    timeout = self.idle()
  File "/home/mauve/.virtualenvs/pyweek3/lib/python3.6/site-packages/pyglet/app/base.py", line 275, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/home/mauve/.virtualenvs/pyweek3/lib/python3.6/site-packages/pyglet/clock.py", line 346, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "src/game.py", line 2330, in timer_callback
    game.timer(dt)
  File "src/game.py", line 414, in timer
    self.logics.advance(dt)
  File "src/game.py", line 287, in advance
    t.advance(1)
  File "src/game.py", line 333, in advance
    if self.callback():
  File "src/game.py", line 658, in _complete
    self.callback()
  File "src/game.py", line 1760, in _animation_finished
    self.animate_if_on_moving_water()
  File "src/game.py", line 1708, in animate_if_on_moving_water
    self.move_with_animation(new_position, water_speed_logics)
  File "src/game.py", line 1631, in move_with_animation
    self.queue_for_tile(position)
  File "src/game.py", line 755, in queue_for_tile
    assert self.queued_tile == None, f"{self} queued_tile is {self.queued_tile}, should be None"
AssertionError: <Log #9 Vec2D(1, 8)> queued_tile is Vec2D(1, 9), should be None
```

**Comment by lordmauve** [comment]
I think the problem is that the base FloatingPlatform class [doesn't care if it is pushed into something|https://github.com/larryhastings/pyweek26/blob/0f75fa9b7e0fd5615bf0ed9bf0d30d965e5d55f1/src/game.py#L1713].

The above change added checking of the response from `on_pushed_into_something()`, but the base class implementation was not changed to veto the movement.
