### ISSUE TITLE
Launcher issue with relative paths

### ISSUE THREAD

**Issue by lordmauve** [larryhastings/pyweek26#25]
The `run_game.py` launcher seems to have a bug where the 'src' path is considered absolute instead of relative to the launcher script itself.

On Windows:

> py -3 run_game.py
> Traceback (most recent call last):
> File "run_game.py", line 26, in <module>
> os.chdir(srcdir)
> FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\src'

On something Posixey:

> Traceback (most recent call last):
> File "run_game.py", line 26, in <module>
> os.chdir(srcdir)
> FileNotFoundError: [Errno 2] No such file or directory: '/src'

**Comment by AhmedAmrMohamed** [comment]
that's a problem regarding how different os treat paths.
replace the file `run_game.py` with this [file](https://github.com/theunderd0g/pyweek26/blob/master/run_game.py) and run again.
Hope it helps.
